import { createServer } from "miragejs"

createServer({
  routes() {
    this.namespace = "api"

    this.get("/data", () => {
      return {
        products: [
          { id: 1,
            category: "Mobile",
            name: "OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM, 128GB Storage)",
            price: 17999,
            brand: "OnePlus",
            bestseller : true,
            about: 
            ["6GB RAM | 128GB ROM",
            "16.74 cm (6.59 inch) Display",
            "64MP Rear Camera | 16MP Front Camera",
            "5000 mAh Battery"],
            image: "https://m.media-amazon.com/images/I/71AvQd3VzqL._SX679_.jpg"},
          { id: 2,
            category: "Mobile",
            name: "Redmi 12 5G (Pastel Blue, 6GB RAM, 128GB Storage) ",
            price: 13499, 
            brand: "Redmi",
            about:
            ["6GB RAM | 128GB ROM | Expandable Upto 1TB",
            "17.25 cm (6.79 inch) Full HD+ Display",
            "50MP + 8MP + 2MP | 8MP Front Camera",
            "5000 mAh Battery",
            "Helio G88 Processor"],
            image: "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/e/a/g/-original-imags37h4prxjazz.jpeg?q=70" },
          { id: 3,
            category: "Mobile",
            name: "realme Narzo N55 (Prime Blue, 4GB RAM, 64GB Storage)",
            description: "", 
            price: 10999, 
            brand: "realme",
            about: 
            ["4GB RAM | 64GB ROM",
            "17.07 cm (6.72 inch) Display",
            "64MP Rear Camera",
            "5000 mAh Battery"],
            image: "https://m.media-amazon.com/images/I/71Ftzmh3XWL._SX679_.jpg" },
          { id: 4,
            category: "Mobile",
            name: "SAMSUNG Galaxy M04 (Light Green, 4GB RAM, 64GB Storage)", 
            price: 7099, 
            brand: "Samsung",
            about: 
            ["4GB RAM | 64GB ROM",
            "16.51 cm (6.5 inch) HD+ Display",
            "13MP + 2MP | 5MP Front Camera",
            "5000 mAh Battery",
            "MediaTek Helio P35 Processor"],
            image: "https://m.media-amazon.com/images/I/814ePfNubRL._SX679_.jpg" },
          { id: 5,
            category: "Mobile",
            name: "OnePlus Nord CE 3 5G (Aqua Surge, 8GB RAM, 128GB Storage)", 
            price: 26999, 
            brand: "OnePlus",
            about: 
            ["8GB RAM | 128GB ROM",
            "17.02 cm (6.7 inch) Display",
            "50MP Rear Camera",
            "5000 mAh Battery"],
            image: "https://m.media-amazon.com/images/I/6175SlKKECL._SX679_.jpg" },
          { id: 6,
            category: "Mobile",
            name: "SAMSUNG Galaxy M34 5G (Midnight Blue, 6GB, 128GB Storage)", 
            price: 18999, 
            brand: "Samsung",
            bestseller: true,
            about: 
            ["6GB RAM | 128GB ROM",
            "16.51 cm (6.5 inch) Display",
            "50MP Rear Camera",
            "6000 mAh Battery"],
            image: "https://m.media-amazon.com/images/I/91fonhAtoAL._SX679_.jpg" },
          { id: 7,
            category: "Mobile",
            name: "APPLE iPhone 14 (Purple, 128 GB)", 
            price: 67999,
            brand: "Apple", 
            about: 
            ["128GB ROM",
            "15.49 cm (6.1 inch) Super Retina XDR Display",
            "12MP + 12MP | 12MP Front Camera",
            "A15 Bionic Chip, 6 Core Processor"],
            image: "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/b/u/f/-original-imaghxa5hvapbfds.jpeg?q=70" },
          { id: 8,
            category: "Mobile",
            name: "SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 8GB RAM, 128GB Storage)", 
            price: 26999, 
            brand: "Samsung",
            about: 
            ["8GB RAM | 128GB ROM | Expandable Upto 1TB",
            "16.51 cm (6.5 inch) Full HD+ Display",
            "12MP + 12MP + 8MP Rear Camera | 32MP Front Camera",
            "4500 mAh Lithium Ion Battery",
            "Exynos Octa Core Processor",
            "Super AMOLED Display | 120 Hz Rate",
            "IP68 Rating"],
            image: "https://m.media-amazon.com/images/I/81vDZyJQ-4L._SY879_.jpg" },
          { id: 9,
            category: "Laptop",
            name: "APPLE 2020 Macbook Air M1 - (8 GB/256 GB SSD/Mac OS Big Sur) MGN63HN/A  (13.3 inch, Space Grey, 1.29 kg)", 
            price: 81990, 
            brand: "Apple",
            about: 
            ["Stylish & Portable Thin and Light Laptop",
            "13.3 inch Quad LED Backlit IPS Display (227 PPI, 400 nits Brightness, Wide Colour (P3), True Tone Technology)",
            "Light Laptop without Optical Disk Drive"],
            image: "https://rukminim2.flixcart.com/image/832/832/kp5sya80/screen-guard/tempered-glass/o/v/n/apple-macbook-air-m1-13-3-inch-lightwings-original-imag3gh5xftgbpg3.jpeg?q=70" },
          { id: 10,
            category: "Laptop",
            name: "HP Victus Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 1650/144 Hz) 15-fa0070TX Gaming Laptop  (15.6 Inch, Performance Blue, 2.37 Kg, With MS Office)", 
            price: 63990, 
            brand: "HP",
            about: 
            ["NVIDIA GeForce GTX 1650",
            "15.6 Inch Full HD, 144 Hz, 9 ms response time, micro-edge, anti-glare, Brightness: 250 nits, 141 ppi, Color Gamut: 45% NTSC ",
            "Light Laptop without Optical Disk Drive",
            "Preloaded with MS Office"],
            image: "https://m.media-amazon.com/images/I/81EgXbp4vaL._SX679_.jpg" },
          { id: 11,
            category: "Laptop",
            name: "ASUS VivoBook 16X Ryzen 7 Octa Core 5800H - (16 GB/512 GB SSD/Windows 11 Home) M1603QA-MB711WS Thin and Light Laptop  (16 Inch, Quiet Blue, 1.80 Kg, With MS Office)", 
            price: 62990, 
            bestseller: true,
            brand: "Asus",
            about: 
            ["Stylish & Portable Thin and Light Laptop",
            "16 Inch WUXGA, IPS-level Panel (Brightness 300nits, 45% NTSC color gamut)",
            "Finger Print Sensor for Faster System Access",
            "Light Laptop without Optical Disk Drive"],
            image: "https://rukminim2.flixcart.com/image/832/832/xif0q/computer/o/7/1/-original-imagpxgrmuazgfce.jpeg?q=70" },
          { id: 12,
            category: "Laptop",
            name: "HP 15s Intel Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home) 15s-fq5111TU Thin and Light Laptop  (15.6 inch, Natural Silver, 1.69 Kg, With MS Office)", 
            price: 54990, 
            brand: "HP",
            about:
            ["Stylish & Portable Thin and Light Laptop",
            "15.6 inch Full HD, micro-edge, anti-glare, UWVA, Brightness: 250 nits, 141 ppi, Color Gamut: 45%NTSC",
            "Light Laptop without Optical Disk Drive"],
            image: "https://m.media-amazon.com/images/I/71A95WmWCeL._SL1500_.jpg" },
          { id: 13,
            category: "Laptop",
            name: "Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home)  Thin and Light Laptop  (15.6 Inch, Grey, 1.7 Kg, With MS Office)", 
            price: 35990, 
            brand: "Lenovo",
            about: 
            ["Stylish & Portable Thin and Light Laptop",
            "15.6 Inch FHD 220nits Anti-glare",
            "Light Laptop without Optical Disk Drive"],
            image: "https://m.media-amazon.com/images/I/51RRfRzyuOL._SX466_.jpg" },
          { id: 14,
            category: "Laptop",
            name: "DELL Vostro Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) Vostro 3420 Notebook  (14 inch, Carbon Black, 1.48 Kg, With MS Office)", 
            price: 37990,
            brand: "Dell", 
            about:
            ["14 inch FHD, WVA AG Narrow Border 250 nits",
            "Light Laptop without Optical Disk Drive"],
            image: "https://m.media-amazon.com/images/I/61G5EPaVmXL._SX679_.jpg" },
          { id: 15,
            category: "Laptop",
            name: "Acer Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) Aspire Lite AL15-51 Thin and Light Laptop  (15.6 inch, Steel Gray)", 
            price: 31999,
            brand: "Acer", 
            about:
            ["Stylish & Portable Thin and Light Laptop",
            "15.6 inch",
            "Light Laptop without Optical Disk Drive"],
            image: "https://m.media-amazon.com/images/I/71czGb00k5L._SL1500_.jpg" },
          { id: 16,
            category: "Laptop",
            name: "ASUS Vivobook 15 Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) X515EA-EJ312W Thin and Light Laptop  (15.6 Inch, Transparent Silver, 1.80 kg)", 
            price: 34990,
            brand: "Asus", 
            about:
            ["Stylish & Portable Thin and Light Laptop",
            "15.6 Inch Full HD anti-glare, Brightness: 200 nits, Color Gamut: 45% NTSC",
            "Finger Print Sensor for Faster System Access",
            "Light Laptop without Optical Disk Drive"],
            image: "https://rukminim2.flixcart.com/image/832/832/xif0q/computer/r/e/f/-original-imagrgprbhchwgve.jpeg?q=70" },
          { id: 17,
            category: "Earphones",
            name: "OnePlus Bullets Wireless Z2 with Fast Charge, 30 Hrs Battery Life, Earphones with mic Bluetooth Headset (Magico Black, In the Ear)", 
            price: 1999, 
            brand: "OnePlus",
            bestseller: true,
            about:
            ["With Mic:Yes",
            "Bluetooth version: 5",
            "Battery life: 20 Hrs | Charging time: 10 mins"],
            image: "https://m.media-amazon.com/images/I/51UhwaQXCpL._SX466_.jpg" },
          { id: 18,
            category: "Earphones",
            name: "boAt Airdopes 131 with upto 60 Hours and ASAP Charge Bluetooth Headset (Active Black, True Wireless)", 
            price: 999, 
            brand: "boat",
            about: 
            ["With Mic:Yes",
            "Bluetooth version: 5.0 / 5.1",
            "Wireless range: 10 Meters",
            "Charging time: 2 Hours",
            "Playback Time: Upto 15 to 60 Hours Playback",
            "ASAP Charge: 5 Mins Charge= 90 Mins Playback",
            "13MM Drivers",
            "IPX4: Sweat Resistance"],
            image: "https://rukminim2.flixcart.com/image/832/832/xif0q/headphone/1/8/l/-original-imagqhswqgpwb2yu.jpeg?q=70" },
          { id: 19,
            category: "Earphones",
            name: "boAt Bassheads 102 Wired in Ear Earphones with Mic (Mint Purple)", 
            price: 499,
            brand: "boat", 
            about: 
            ["With Mic:Yes",
            "Super Extra Bass",
            "Passive Noise Cancellation",
            "10MM Drivers",],
            image: "https://m.media-amazon.com/images/I/51CxVGGzHjL._SX466_.jpg" },
          { id: 20,
            category: "Earphones",
            name: "boAt Nirvana 751 ANC Hybrid Active Noise Cancelling Bluetooth Wireless Over Ear Headphones with Up to 65H Playtime, ASAP Charge (Gunmetal Grey)", 
            price: 4499, 
            brand: "boat",
            about: 
            ["With Mic:Yes",
            "Bluetooth version: 5.0",
            "Wireless range: 10 Meters",
            "Charging Time : 1 Hour",
            "Playback Time :65 Hours (54 Hours with ANC)",
            "40MM Drivers"],
            image: "https://m.media-amazon.com/images/I/71ISIssoVFL._SX466_.jpg" },
          { id: 21,
            category: "Earphones",
            name: "SONY WH-1000XM4 Bluetooth Headset  (Black, On the Ear)", 
            price: 19988, 
            brand: "Sony",
            about: 
            ["With Mic:Yes",
            "Bluetooth version: 5.0",
            "Digital Noise Cancellation",
            "10 min charge for 5 hours of playback",
            "40MM Drivers"],
            image: "https://rukminim2.flixcart.com/image/832/832/l1dwknk0/headphone/b/f/2/wh-1000xm4-sony-original-imagcywfhzq8hx2z.jpeg?q=70" },
          { id: 22,
            category: "Earphones",
            name: "OnePlus Nord Buds 2 True Wireless Earbuds with 25dB Active Noise Cancellation Bluetooth Headset  (Thunder Gray, True Wireless)", 
            price: 2799,
            brand: "OnePlus",
            about: 
            ["With Mic:Yes",
            "Bluetooth version: 5.3",
            "Wireless range: 10 Meters",
            "Battery life: 36 Hours | Charging time: 60 min (Earphone), 90 min (Earphone and Case)",
            "12.4MM dynamic Drivers"],
            image: "https://m.media-amazon.com/images/I/61-ZYvldY+L._SX679_.jpg" },
          { id: 23,
            category: "Earphones",
            name: "boAt Bassheads 100 Wired Headset  (Black, In the Ear)", 
            price: 399,
            brand: "boat", 
            about: 
            ["With Mic:Yes",
            "Connector type: 3.5",
            "Tangle free Cable",
            "Hawk Inspired Design",
            "Super Extra Bass",
            "Easy Integrated controls with Mic"],
            image: "https://m.media-amazon.com/images/I/719elVA3FvL._SX466_.jpg" },
          { id: 24,
            category: "Earphones",
            name: "realme Buds Air 5 Pro Truly Wireless in-Ear Earbuds(Sunrise Beige)", 
            price: 4999,
            brand: "boat", 
            about: 
            ["realBoost Dual Drivers",
            "50dB Active Noise Cancellation",
            "360° Spatial Audio Effect",
            "Playback Time: Upto 40 Hours Playback",
            "IPX5 Water Resistant"],
            image: "https://m.media-amazon.com/images/I/61aVafBbckL._SX679_.jpg" },
          { id: 25,
            category: "Watch",
            name: "APPLE Watch SE GPS (2nd Gen) Heart Rate Monitor, Crash Detection, Sleep Tracking (Starlight Sport Strap, 40mm)", 
            price: 27900, 
            brand: "Apple",
            about: 
            ["Bluetooth Calling",
            "Touchscreen",
            "Fitness & Outdoor",
            "Battery Runtime: Upto 18 hrs"],
            image: "https://m.media-amazon.com/images/I/71YdE55GwjL._SX679_.jpg" },
          { id: 26,
            category: "Watch",
            name: "APPLE Watch Series 8 GPS with ECG app, Temperature sensor, IPX6, Fall/Crash Detection (Midnight Strap, Regular)", 
            price: 45900, 
            brand: "Apple",
            about: 
            ["Bluetooth Calling",
            "Touchscreen",
            "Fitness & Outdoor",
            "Battery Runtime: Upto 18 hrs"],
            image: "https://m.media-amazon.com/images/I/71XMTLtZd5L._SL1500_.jpg" },
          { id: 27,
            category: "Watch",
            name: "beatXP Marv Neo 1.85 inch HD Screen 240*280px One-Tap BT 5.1 Calling AI Voice Assistant Smartwatch (Rose Gold Strap, Free Size)", 
            price: 1399,
            brand: "beatXP",
            about: 
            ["Bluetooth Calling",
            "Touchscreen",
            "Fitness & Outdoor",
            "Battery Runtime: Upto 7 days"], 
            image: "https://m.media-amazon.com/images/I/61FMDYSzhrL._SL1500_.jpg" },
          { id: 28,
            category: "Watch",
            name: "Fire-Boltt Ninja Calling Pro Plus 1.83 inch Display Smartwatch Bluetooth Calling, AI Voice Smartwatch (Black Strap, Free Size)", 
            price: 1299,
            brand: "Fire-Boltt", 
            bestseller: true,
            about: 
            ["Bluetooth Calling",
            "240*286 Pixel High Resolution",
            "Touchscreen",
            "Fitness & Outdoor",
            "120 Sports Modes to Track with IP67 Water Resistant",
            "Battery Runtime: Upto 5 days"], 
            image: "https://m.media-amazon.com/images/I/61BY9Mhhj2L._SL1500_.jpg" },
          { id: 29,
            category: "Watch",
            name: "Fire-Boltt Phoenix Ultra Luxury Stainless Steel, Bluetooth Calling Smartwatch, AI Voice Assistant, Metal Body with 120+ Sports Modes, SpO2, Heart Rate Monitoring (Multicolor)", 
            price: 1947,
            brand: "Fire-Boltt", 
            about: 
            ["Bluetooth Calling",
            "Full Touch Screen and 240*240 Pixel High Resolution",
            "Fitness & Outdoor",
            "120 Sports Modes to Track",
            "Battery Runtime: Upto 4 days"], 
            image: "https://m.media-amazon.com/images/I/71D7jU3tUUL._SL1500_.jpg" },
          { id: 30,
            category: "Watch",
            name: "boAt Wave Call 2 Smart Watch with 1.83 inch HD Display, Advanced BT Calling, DIY Watch Face Studio, 700+Active Modes, HR&SPO2 and Sleep Monitoring(Silver Metal)", 
            price: 1599, 
            brand: "boat",
            about: 
            ["Bluetooth Calling",
            "Fitness & Outdoor(700+ Active Modes)",
            "DIY Watch Face Studio",
            "Heart rate and SpO2 Monitoring"], 
            image: "https://m.media-amazon.com/images/I/81Pu0heqmfL._SX679_.jpg" }
        ],
        brands: {
          Mobile: ["Apple","Redmi","realme","OnePlus","Samsung"],
          Laptop: ["Acer","Apple","Asus","Dell","HP","Lenovo"],
          Earphones: ["OnePlus","boat","Sony"],
          Watch: ["Apple","beatXP","Fire-Boltt","boat"]
        }
      }
    })

  },
})